### ISSUE TITLE
Custom Title Bar color match

### ISSUE THREAD

**Issue by ghost** [olifink/vscode-fedora-gnome-theme#2]
When using the Custom Title Bar the color doesn't match, is there a way to change this?
![image](https://user-images.githubusercontent.com/57453593/119076765-70777300-b9f3-11eb-9ca0-da14ace5386e.png)

**Comment by olifink** [comment]
good catch: yes, that should be possible. I mostly use 'native' style so I see that now - also the custom menu background colors seem to pick that up.

I'll check that and update the colors and hopefully will come around to uploading a new version over the weekend

**Comment by olifink** [comment]
ok, I just pushed the new version 0.0.4 to Marketplace and Open VSX which uses the matching colors for the custom title bar style and menus

**Comment by ghost** [comment]
Looking great now, thank you very much!
